spring.application.name=tripGoAPI

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tripgo
spring.datasource.username=root
spring.datasource.password=Aa@123456

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration